// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace GithubTrending.Api
{
    public partial class AuditLogDbContextModel
    {
        partial void Initialize()
        {
            var auditLog = AuditLogEntityType.Create(this);

            AuditLogEntityType.CreateAnnotations(auditLog);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.1");
            AddAnnotation("Relational:DefaultSchema", "auditlog");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
