version: '3.4'

services:
  
  #####################################
  # Postgres
  #####################################
  postgresql:
    ports:
      - 5436:5432
    networks:
      - netcore-example
  
  #####################################
  # Blog Api
  #####################################
  netcorexamples.blogapi:
    env_file:
      - ./resources/env
    ports:
      - "5400:80"
    networks:
      - netcore-example
  
  #####################################
  # FileManagement
  #####################################
  netcorexamples.filemangement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5401:80"
    networks:
      - netcore-example
  
  #####################################
  # Iced Tea
  #####################################
  netcorexamples.icedtea:
    env_file:
      - ./env/env.icedtea
    ports:
      - "5402:80"
    networks:
      - netcore-example

networks:
  netcore-example:
    external: true