version: '3.4'

services:
  #####################################
  # Postgres
  #####################################
  postgresql:
    container_name: postgres_example
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: Mramra1234!@
    volumes:
      - netcorexamples-data:/var/lib/postgresql/data
    command: postgres -N 500
  
  #####################################
  # Blog Api
  #####################################
  netcorexamples.blogapi:
    container_name: netcorexamples.blogapi
    image: netcorexamples_blogapi
    build:
      context: .
      dockerfile: src/blogs/Blog.Api/Dockerfile
  
  #####################################
  # FileManagement
  #####################################
  netcorexamples.filemangement:
    container_name: netcorexamples.filemangement
    image: netcorexamples_filemangement
    build:
      context: .
      dockerfile: src/filemanagement/FileManagement/Dockerfile
  
  #####################################
  # Iced Tea
  #####################################
  netcorexamples.icedtea:
    container_name: netcorexamples.icedtea
    image: netcorexamples_icedtea
    build:
      context: .
      dockerfile: src/icedtea/IcedTea.Api/Dockerfile

volumes:
  netcorexamples-data:
    external: true    