version: '3.4'

services:
#####################################
# Postgres
#####################################
  postgresql:
    container_name: postgres_example
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: Mramra1234!@
    volumes:
      - blog-data:/var/lib/postgresql/data
    command: postgres -N 500

#####################################
# Blog Api
#####################################
  netcorexamples.blogapi:
    container_name: netcorexamples_blogapi
    image: netcorexamples_blogapi
    build:
      context: .
      dockerfile: src/blogs/Blog.Api/Dockerfile        


volumes:
  blog-data:
    external: true    