// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Blog.Api
{
    public partial class BlogDbContextModel
    {
        partial void Initialize()
        {
            var blog = BlogEntityType.Create(this);
            var blogTag = BlogTagEntityType.Create(this);
            var tag = TagEntityType.Create(this);

            BlogTagEntityType.CreateForeignKey1(blogTag, blog);
            BlogTagEntityType.CreateForeignKey2(blogTag, tag);

            BlogEntityType.CreateAnnotations(blog);
            BlogTagEntityType.CreateAnnotations(blogTag);
            TagEntityType.CreateAnnotations(tag);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0");
            AddAnnotation("Relational:DefaultSchema", "blog");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
