// <auto-generated />
using Blog.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Blog.Api
{
    [DbContext(typeof(BlogDbContext))]
    public partial class BlogDbContextModel : RuntimeModel
    {
        static BlogDbContextModel()
        {
            var model = new BlogDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static BlogDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
