// <auto-generated />
using System;
using GithubTrending.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GithubTrending.Api.Data.Migrations.GithubTrending
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220406071506_InitialGithubTrending")]
    partial class InitialGithubTrending
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("github_repositories")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GithubTrending.Domain.AggregateModel.GithubRepositoriesAggregate.GithubRepositories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ForkCount")
                        .HasColumnType("text")
                        .HasColumnName("fork_count");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by_id");

                    b.Property<DateTimeOffset>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_date");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("OwnersTwitterAccount")
                        .HasColumnType("text")
                        .HasColumnName("owners_twitter_account");

                    b.Property<string>("Repository")
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<string>("StarCount")
                        .HasColumnType("text")
                        .HasColumnName("star_count");

                    b.Property<int>("StatusGithubTrending")
                        .HasColumnType("integer")
                        .HasColumnName("status_github_trending");

                    b.Property<string>("TodayStarCount")
                        .HasColumnType("text")
                        .HasColumnName("today_star_count");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_github_trending");

                    b.ToTable("github_trending", "github_repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
