// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Shared.Audit;

#pragma warning disable 219, 612, 618
#nullable enable

namespace IcedTea.Api
{
    [DbContext(typeof(AuditLogDbContext))]
    public partial class AuditLogDbContextModel : RuntimeModel
    {
        static AuditLogDbContextModel()
        {
            var model = new AuditLogDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static AuditLogDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
