// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace GithubTrending.Api
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var githubRepositories = GithubRepositoriesEntityType.Create(this);

            GithubRepositoriesEntityType.CreateAnnotations(githubRepositories);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.1");
            AddAnnotation("Relational:DefaultSchema", "github_repositories");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
