// <auto-generated />
using IcedTea.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace IcedTea.Api
{
    [DbContext(typeof(LogDbContext))]
    public partial class LogDbContextModel : RuntimeModel
    {
        static LogDbContextModel()
        {
            var model = new LogDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static LogDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
